POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json
###
GET http://localhost:8081/comment/getAll
Content-Type: application/json

###
###
GET http://localhost:8081/comment/getAll
Content-Type: application/json

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

###
POST http://localhost:8081/comment/editComment
Content-Type: application/json 

{
   "_id":"643e3fdb579b41b6a62506e6",
   "username":"junior18",
   "stationName":"northstation",
   "comment":"junior t."
}
###
POST http://localhost:8081/users/507f1f77bcf86cd799439011/favorites
Content-Type: application/json
{
  "stopName": "Test Stop",
  "line": "Test Line",
  "stopId": "teststop1",
  "arrivalTime": "2023-05-15T15:30:00Z",
  "lineColor": "#FF0000",
  "lineName": "Test Line",
  "destination": "Test Destination"
}